// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetRoomByCode(ctx context.Context, roomCode string) (Room, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListActiveRooms(ctx context.Context, arg ListActiveRoomsParams) ([]Room, error)
	UpdateRoomPlayers(ctx context.Context, arg UpdateRoomPlayersParams) error
	UpdateUserStats(ctx context.Context, arg UpdateUserStatsParams) error
}

var _ Querier = (*Queries)(nil)
