// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (room_code, room_name, room_type, game_mode, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, room_code, room_name, room_type, game_mode, created_by, is_active, max_players, current_players, created_at, started_at, ended_at
`

type CreateRoomParams struct {
	RoomCode  string      `json:"room_code"`
	RoomName  string      `json:"room_name"`
	RoomType  string      `json:"room_type"`
	GameMode  string      `json:"game_mode"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.RoomCode,
		arg.RoomName,
		arg.RoomType,
		arg.GameMode,
		arg.CreatedBy,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.RoomCode,
		&i.RoomName,
		&i.RoomType,
		&i.GameMode,
		&i.CreatedBy,
		&i.IsActive,
		&i.MaxPlayers,
		&i.CurrentPlayers,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getRoomByCode = `-- name: GetRoomByCode :one
SELECT id, room_code, room_name, room_type, game_mode, created_by, is_active, max_players, current_players, created_at, started_at, ended_at FROM rooms
WHERE room_code = $1 LIMIT 1
`

func (q *Queries) GetRoomByCode(ctx context.Context, roomCode string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByCode, roomCode)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.RoomCode,
		&i.RoomName,
		&i.RoomType,
		&i.GameMode,
		&i.CreatedBy,
		&i.IsActive,
		&i.MaxPlayers,
		&i.CurrentPlayers,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const listActiveRooms = `-- name: ListActiveRooms :many
SELECT id, room_code, room_name, room_type, game_mode, created_by, is_active, max_players, current_players, created_at, started_at, ended_at FROM rooms
WHERE is_active = true
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListActiveRoomsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListActiveRooms(ctx context.Context, arg ListActiveRoomsParams) ([]Room, error) {
	rows, err := q.db.Query(ctx, listActiveRooms, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.RoomCode,
			&i.RoomName,
			&i.RoomType,
			&i.GameMode,
			&i.CreatedBy,
			&i.IsActive,
			&i.MaxPlayers,
			&i.CurrentPlayers,
			&i.CreatedAt,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoomPlayers = `-- name: UpdateRoomPlayers :exec
UPDATE rooms
SET current_players = $2
WHERE id = $1
`

type UpdateRoomPlayersParams struct {
	ID             pgtype.UUID `json:"id"`
	CurrentPlayers pgtype.Int4 `json:"current_players"`
}

func (q *Queries) UpdateRoomPlayers(ctx context.Context, arg UpdateRoomPlayersParams) error {
	_, err := q.db.Exec(ctx, updateRoomPlayers, arg.ID, arg.CurrentPlayers)
	return err
}
