// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, username, email, password_hash, avatar_url, created_at, updated_at, is_active, total_points, total_games, win_streak
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.TotalPoints,
		&i.TotalGames,
		&i.WinStreak,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, avatar_url, created_at, updated_at, is_active, total_points, total_games, win_streak FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.TotalPoints,
		&i.TotalGames,
		&i.WinStreak,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, avatar_url, created_at, updated_at, is_active, total_points, total_games, win_streak FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.TotalPoints,
		&i.TotalGames,
		&i.WinStreak,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, avatar_url, created_at, updated_at, is_active, total_points, total_games, win_streak FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.TotalPoints,
		&i.TotalGames,
		&i.WinStreak,
	)
	return i, err
}

const updateUserStats = `-- name: UpdateUserStats :exec
UPDATE users
SET total_points = total_points + $2,
    total_games = total_games + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateUserStatsParams struct {
	ID          pgtype.UUID `json:"id"`
	TotalPoints pgtype.Int4 `json:"total_points"`
}

func (q *Queries) UpdateUserStats(ctx context.Context, arg UpdateUserStatsParams) error {
	_, err := q.db.Exec(ctx, updateUserStats, arg.ID, arg.TotalPoints)
	return err
}
