// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Room struct {
	ID             pgtype.UUID      `json:"id"`
	RoomCode       string           `json:"room_code"`
	RoomName       string           `json:"room_name"`
	RoomType       string           `json:"room_type"`
	GameMode       string           `json:"game_mode"`
	CreatedBy      pgtype.UUID      `json:"created_by"`
	IsActive       pgtype.Bool      `json:"is_active"`
	MaxPlayers     pgtype.Int4      `json:"max_players"`
	CurrentPlayers pgtype.Int4      `json:"current_players"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	StartedAt      pgtype.Timestamp `json:"started_at"`
	EndedAt        pgtype.Timestamp `json:"ended_at"`
}

type User struct {
	ID           pgtype.UUID      `json:"id"`
	Username     string           `json:"username"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	AvatarUrl    pgtype.Text      `json:"avatar_url"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	IsActive     pgtype.Bool      `json:"is_active"`
	TotalPoints  pgtype.Int4      `json:"total_points"`
	TotalGames   pgtype.Int4      `json:"total_games"`
	WinStreak    pgtype.Int4      `json:"win_streak"`
}
